server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: ai-love-system
  
  profiles:
    active: dev
  
  datasource:
    url: jdbc:mysql://localhost:3306/ai_love_system?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    open-in-view: false
  
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai
    default-property-inclusion: non_null
  
  cache:
    type: simple
  
  ai:
    openai:
      api-key: f75d72ba78684960807a3655306b6dca.Hrv8UWXj1d75pKKH
      base-url: https://open.bigmodel.cn/api/paas/v4/
      chat:
        options:
          model: glm-4-flash
          temperature: 0.7
          max-tokens: 2048

# 应用自定义配置
app:
  jwt:
    secret: ai-love-system-jwt-secret-key-2024
    expiration: 86400000 # 24小时
  
  ai:
    zhipu:
      api-key: f75d72ba78684960807a3655306b6dca.Hrv8UWXj1d75pKKH
      model: glm-4-flash
      max-tokens: 2048
      temperature: 0.7
  
  cors:
    allowed-origins: 
      - http://localhost:3000
      - http://localhost:5173
      - http://127.0.0.1:3000
      - http://127.0.0.1:5173
    allowed-methods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
    allowed-headers: "*"
    allow-credentials: true

# 日志配置
logging:
  level:
    com.ai.love: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/ai-love-system.log

# Swagger文档配置
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  packages-to-scan: com.ai.love.controller

# 管理端点配置
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized
